package words

// sixPacks is an editorial bank. Six-letter entries used to be assembled with
// the same placeholder copy; each entry below now has a specific definition
// and two graduated clues.
func sixPacks() []Pack {
	type entry struct{ word, definition, clueOne, clueTwo, difficulty string }
	type group struct {
		id, title, blurb, connection string
		entries                      []entry
	}
	f := func(w, d, a, b string) entry { return entry{w, d, a, b, "familiar"} }
	s := func(w, d, a, b string) entry { return entry{w, d, a, b, "stretch"} }
	groups := []group{
		{"night-sky", "Night Sky", "Things that make the dark look occupied.", "Each word names something seen in, or associated with, the night sky.", []entry{
			f("comets", "Icy bodies that grow bright tails near the sun.", "It can return after a very long orbit.", "A glowing tail is its calling card."), s("aurora", "A shifting display of coloured light near the poles.", "It is most at home near the Arctic and Antarctic.", "Solar activity can make it brighter."), s("nebula", "A cloud of gas and dust in space.", "It is far larger than any ordinary cloud.", "Stars can form inside one."), f("planet", "A large body that travels around a star.", "Earth is one of these.", "It circles a star rather than shining by itself."), s("meteor", "A streak of light made by space debris burning in the atmosphere.", "People sometimes call it a shooting star.", "It is a brief flash high overhead."),
		}},
		{"on-stage", "On Stage", "Words from the side of a performance.", "Each word belongs to making or presenting live music and theatre.", []entry{
			s("chorus", "A repeated part of a song, or a group that sings together.", "A crowd may know this part best.", "It usually returns between verses."), f("melody", "A sequence of notes that forms a tune.", "You can carry this even without lyrics.", "It is the tune rather than the beat."), s("rhythm", "A pattern of beats and pauses in sound or movement.", "Clapping can establish this.", "It gives music its pulse."), s("encore", "An extra performance requested after the scheduled ending.", "It happens when the audience will not let the show end.", "A performer returns for one more piece."), f("actors", "People who perform characters in a play, film or show.", "They take on parts written by someone else.", "A cast is made up of these people."),
		}},
		{"by-water", "By Water", "A small coast in five words.", "Each word belongs to travel, work or wayfinding by the sea.", []entry{
			s("beacon", "A signal light or marker used to guide people.", "It is meant to be noticed from far away.", "A lighthouse is one kind of this."), s("harbor", "A sheltered place where boats can moor safely.", "Boats seek this when the water turns rough.", "It offers shelter beside a coast."), f("sailor", "A person who works or travels on a vessel.", "They know a ship’s routines.", "Their workplace moves across water."), s("voyage", "A long journey, especially by sea.", "It sounds more deliberate than a quick trip.", "Historically it often meant a sea journey."), f("island", "Land surrounded by water.", "It has a shoreline in every direction.", "It can be tiny or continental in scale."),
		}},
		{"printed-page", "Printed Page", "Parts of a story before it becomes one.", "Each word concerns writing, books or the page itself.", []entry{
			s("author", "A person who writes a book, article or other work.", "This person’s name may appear on a book’s cover.", "They are credited with making the work."), f("volume", "A bound book, or one book in a series.", "A long series may have many of these.", "In a library, it is a single bound item."), f("leafed", "Having leaves, or having turned through pages quickly.", "You might do this while looking for a picture.", "It can describe a plant or a book."), s("margin", "The blank edge around printed text.", "Notes are often written here.", "It is the quiet space around a page’s main text."), s("phrase", "A short group of words that forms part of a sentence.", "It is shorter than a full sentence.", "People may borrow a memorable one."),
		}},
		{"garden-work", "Garden Work", "The patient parts of growing things.", "Each word belongs to tending plants or the tools used to do it.", []entry{
			f("petals", "The coloured parts that surround a flower’s centre.", "They are softer than a flower’s green outer parts.", "A rose sheds these one by one."), f("shovel", "A tool with a broad blade for lifting loose material.", "It helps move soil from one place to another.", "Its blade is wider than a digging fork."), s("trowel", "A small hand tool with a pointed blade for soil or mortar.", "It fits comfortably in one hand.", "It makes a hole for a seedling."), f("seeded", "Having produced or been planted with seeds.", "A lawn may be this after a bare patch is repaired.", "It begins a plant’s life from its smallest package."), s("pruned", "Cut back to improve a plant’s growth or shape.", "It is selective cutting, not mowing.", "Fruit trees often benefit from this in winter."),
		}},
		{"cold-weather", "Cold Weather", "A forecast with its collar up.", "Each word belongs to winter weather or moving through it.", []entry{
			f("frosty", "Covered with frost or sharply cold.", "It may decorate grass before sunrise.", "A cold greeting can be described this way."), s("flurry", "A brief burst of snow, wind or activity.", "It often arrives quickly and passes quickly.", "Snow can fall in one without settling."), f("winter", "The coldest season of the year in temperate climates.", "It follows autumn in the northern hemisphere.", "Days are shortest during this season."), s("icicle", "A pointed piece of ice that forms as dripping water freezes.", "It can hang from a roof after a thaw.", "It is a frozen drip with a sharp point."), s("sleigh", "A vehicle on runners, usually pulled across snow.", "It travels best when roads are covered white.", "It slides rather than rolls."),
		}},
		{"at-home", "At Home", "Objects that earn their keep indoors.", "Each word names a familiar object or feature of a home.", []entry{
			f("pillow", "A soft support for the head while resting.", "It waits at the head of a bed.", "A good one affects your neck in the morning."), f("kettle", "A container used to boil water.", "Tea often begins with this on the stove.", "It is built to heat water."), f("drawer", "A sliding storage compartment in furniture.", "Socks and cutlery often live in one.", "It opens by pulling rather than swinging."), f("carpet", "A woven covering for a floor.", "It makes a room quieter underfoot.", "It can cover a floor wall to wall."), f("window", "An opening in a wall that admits light and air.", "Rain makes patterns on its glass.", "It connects a room to what is outside."),
		}},
		{"in-the-city", "In The City", "The pieces that make a place feel busy.", "Each word names a place or system commonly found in a city.", []entry{
			f("street", "A public road in a town or city.", "Addresses commonly begin with one.", "Cars, bicycles and pedestrians may share it."), f("subway", "An underground railway, or underground pedestrian passage.", "It runs below a city’s surface.", "A map of coloured lines may guide you through it."), f("market", "A place where people buy and sell goods.", "Stalls may sell food, cloth or flowers here.", "Prices are often discussed aloud in one."), f("museum", "A building that preserves and displays objects of interest.", "You might see paintings, fossils or tools there.", "It keeps objects for the public to encounter."), f("arcade", "A covered passage with shops, or a row of arches.", "It can shelter shoppers from rain.", "It may mean a passage or a game venue."),
		}},
		{"on-the-road", "On The Road", "Ways of moving through a journey.", "Each word belongs to making, changing or navigating a journey.", []entry{
			f("ticket", "A record that gives someone permission to travel or enter.", "A conductor may ask to see this.", "It proves you have paid for a seat or entry."), f("engine", "A machine that turns energy into motion.", "It sits under a car’s hood.", "Fuel or electricity can make it move."), f("travel", "To go from one place to another.", "It can be for work, pleasure or necessity.", "A suitcase is often involved."), f("detour", "A longer route taken to avoid a blocked direct one.", "Roadworks can force one.", "It takes you around an interruption."), s("tarmac", "A hard road surface, often used for airport paving.", "Aircraft may wait on this before takeoff.", "It is the dark hard surface beside a runway."),
		}},
		{"kitchen-table", "Kitchen Table", "The useful grammar of cooking.", "Each word belongs to preparing, seasoning or serving food.", []entry{
			f("recipe", "A set of instructions for preparing a dish.", "It tells you what to combine and when.", "A dish can be followed from one."), f("ladles", "Deep long-handled spoons for serving liquid food.", "They move soup from pot to bowl.", "They are deeper than an ordinary spoon."), f("simmer", "To cook a liquid just below boiling.", "A stew benefits from this patient heat.", "It is quieter than a rolling boil."), f("pepper", "A pungent spice made from dried berries, or a plant with hollow fruits.", "A grinder beside salt may hold it.", "It can be a spice or a vegetable."), f("saucer", "A small shallow dish placed under a cup.", "It catches a spill below a teacup.", "It is flatter than the cup it supports."),
		}},
		{"weather-watch", "Weather Watch", "A day deciding what sort it will be.", "Each word describes changing weather or a visible result of it.", []entry{
			f("breeze", "A gentle wind.", "It can cool you without moving branches much.", "It is more pleasant than a gale."), f("cloudy", "Covered with clouds or lacking clarity.", "Sunlight may be present but muted.", "It is the forecast opposite of clear."), f("stormy", "Marked by strong wind, rain or severe weather.", "Umbrellas have a difficult time in this.", "It describes a threatening sky."), f("sunset", "The daily disappearance of the sun below the horizon.", "It brings the day toward evening.", "People often stop to photograph it."), f("melted", "Changed from solid to liquid through warmth.", "An ice cube does this in a warm drink.", "Heat turns something solid into a flow."),
		}},
		{"small-creatures", "Small Creatures", "Animals that make their presence known.", "Each word names a small animal or insect encountered in ordinary life.", []entry{
			s("beetle", "An insect with hard front wings covering its flying wings.", "It has a shell-like pair of wing covers.", "A ladybird belongs to this group."), s("weevil", "A small beetle with an elongated snout.", "It may turn up where flour or rice is stored.", "Its narrow snout distinguishes it from many beetles."), f("rabbit", "A small long-eared mammal that moves by hopping.", "It may live in a burrow.", "Its ears are longer than its front legs."), f("otters", "Water-loving mammals with dense fur.", "They can be seen sliding into rivers.", "Some hold hands while resting in water."), f("insect", "A small animal with six legs and three main body sections.", "A butterfly and an ant both fit this group.", "Its body has head, thorax and abdomen."),
		}},
		{"workshop", "Workshop", "Tools and the marks they leave behind.", "Each word belongs to shaping wood, stone or other materials by hand.", []entry{
			f("hammer", "A tool with a heavy head for striking objects.", "It drives a nail into wood.", "Its force comes from a swing."), s("chisel", "A sharp-edged tool used to cut or shape hard material.", "A mallet may strike its handle.", "It removes material in controlled chips."), f("sawing", "Cutting material with a toothed blade.", "It leaves fine dust when used on wood.", "Teeth on a blade do the cutting."), f("sander", "A tool that smooths a surface with abrasive material.", "It prepares wood before paint or varnish.", "It trades roughness for fine dust."), s("planer", "A tool or machine that makes wood flatter and thinner.", "It removes a thin layer from a board.", "Wood curls may collect beside it."),
		}},
		{"good-argument", "Good Argument", "The ingredients of changing a mind.", "Each word belongs to reasoning through a disagreement with someone.", []entry{
			f("reason", "A fact or idea offered in support of a conclusion.", "You may ask someone to give one for a decision.", "It connects evidence to a claim."), f("debate", "A formal discussion in which opposing views are argued.", "Two sides take turns making a case.", "A moderator may keep this orderly."), f("proofs", "Evidence or arguments that establish something as true.", "Mathematicians build these step by step.", "They are evidence strong enough to settle a claim."), f("listen", "To pay attention to sound or another person’s words.", "It is required before a reply can be thoughtful.", "Good conversation needs this before speaking."), s("assent", "Agreement with a statement, proposal or decision.", "A nod can show this without words.", "It is a formal word for saying yes to an idea."),
		}},
		{"at-the-match", "At The Match", "Words that arrive with a scoreboard.", "Each word belongs to organised competition, its equipment or its officials.", []entry{
			f("sports", "Games and physical contests played for recreation or competition.", "Teams or individuals may compete in these.", "A scoreboard usually belongs to one."), f("league", "An organised group of teams that compete regularly.", "A season’s table may rank these teams.", "It puts clubs into one competition."), f("racket", "A handled frame with strings used to hit a ball or shuttlecock.", "Tennis players swing one.", "Its strings meet the ball."), s("umpire", "An official who makes decisions in a game or dispute.", "They call balls and strikes in baseball.", "They are meant to be neutral."), f("medals", "Small metal awards given for achievement.", "Podium finishers may receive these.", "Gold, silver and bronze are familiar versions."),
		}},
		{"colour-notes", "Colour Notes", "Names for what light has been doing.", "Each word names a colour or pigment used to describe what we see.", []entry{
			f("yellow", "The colour between green and orange in the spectrum.", "A ripe banana is often this colour.", "It sits between green and orange."), f("orange", "The colour between red and yellow, and a citrus fruit.", "It can name a fruit or a colour.", "A traffic cone uses this shade for visibility."), s("violet", "A bluish-purple colour, or the small flowering plant of that colour.", "It is named after a delicate flower.", "It is closer to blue than purple is."), s("indigo", "A deep blue dye traditionally made from certain plants.", "Jeans were traditionally coloured with this dye.", "It is a dark blue with a long trade history."), s("sienna", "An earthy reddish-brown pigment.", "Painters may use a burnt version of it.", "It is named for an Italian city."),
		}},
		{"time-keepers", "Time Keepers", "Ways we arrange a day into parts.", "Each word names a unit, period or recurring division of time.", []entry{
			f("minute", "A unit equal to sixty seconds.", "There are sixty of these in an hour.", "A clock’s long hand measures these."), f("second", "A unit equal to one sixtieth of a minute.", "It is the smallest common unit on a stopwatch.", "A clock’s fastest hand marks these."), f("season", "A period of the year with typical weather or activity.", "Spring is one of four of these in many climates.", "It can refer to weather or a series of games."), f("spring", "The season after winter and before summer.", "New growth appears during this season.", "It follows winter in a four-season year."), f("autumn", "The season between summer and winter.", "Leaves often change colour in this season.", "It comes before winter."),
		}},
		{"human-scale", "Human Scale", "Words for the texture of ordinary life.", "Each word concerns people, their relationships or the small signals between them.", []entry{
			f("friend", "A person with whom one has a bond of mutual affection.", "They may know your stories without needing the beginning.", "This relationship is chosen rather than inherited."), f("family", "People related by birth, marriage or shared home.", "It may be made by birth, choice or both.", "A household can be one form of this."), f("smiles", "Expressions made by lifting the corners of the mouth.", "They can be genuine, nervous or polite.", "You can see these before a person says anything."), f("voices", "The sounds people use to speak or sing.", "A choir blends several of these.", "It can mean sound, style or influence."), f("kindly", "In a kind, warm or considerate way.", "It describes the tone of a generous reply.", "It is how someone may speak to a stranger in need."),
		}},
		{"open-country", "Open Country", "A walk with more horizon than walls.", "Each word names a feature of a wide outdoor landscape.", []entry{
			s("meadow", "A field of grass, often with wildflowers.", "It is open ground softer than a forest.", "Wildflowers may fill it in summer."), f("valley", "Low land between hills or mountains, often with a river.", "A river may run along its floor.", "It lies between higher ground."), f("forest", "A large area chiefly covered with trees.", "A canopy shades the ground below.", "It is broader and denser than a grove."), s("summit", "The highest point of a hill or mountain.", "Climbers aim to stand here.", "It is the top of a mountain route."), s("canyon", "A deep narrow valley with steep sides.", "A river may have cut it over centuries.", "Its walls are much steeper than a valley’s."),
		}},
		{"quiet-arts", "Quiet Arts", "Making something slowly and by hand.", "Each word names a maker or the act of creating a finished work.", []entry{
			s("weaver", "A person who makes cloth by interlacing threads.", "They work threads over and under one another.", "A loom is their central tool."), s("potter", "A person who makes vessels from clay.", "They shape wet clay into useful forms.", "A kiln finishes much of their work."), f("sketch", "A quick simple drawing that captures an idea.", "It may be made before a finished artwork.", "It favours a quick impression over detail."), f("writer", "A person who creates text for readers.", "They turn thoughts into pages.", "Their material is language."), f("design", "A plan for the appearance or construction of something.", "It begins before an object is made.", "It joins how something works with how it looks."),
		}},
	}
	out := make([]Pack, 0, len(groups))
	for _, group := range groups {
		pack := Pack{ID: group.id, Title: group.title, Blurb: group.blurb, ConnectionDifficulty: "medium"}
		for _, item := range group.entries {
			pack.Words = append(pack.Words, PackWord{Word: item.word, Register: RegisterStandard, Difficulty: item.difficulty, Definition: item.definition, Note: item.definition + " In this set, it helps reveal the shared subject.", Hints: []string{item.clueOne, item.clueTwo}, Connection: group.connection})
		}
		out = append(out, pack)
	}
	return out
}
