/**
 * Keeps the figures in README.md equal to the answer bank.
 *
 *   node scripts/sync-readme.mjs           rewrite the block between the markers
 *   node scripts/sync-readme.mjs --check   exit 1 if the README is out of date
 *
 * Everything between the bank-stats markers is generated; edit this script, not
 * the block. `make test` runs the check, so a change to the bank cannot land
 * with stale numbers in the README.
 */
import { readFile, writeFile } from "node:fs/promises";
import { bankFigures } from "./bank-lib.mjs";

const README = new URL("../../README.md", import.meta.url);
const START = "<!-- bank-stats:start -->";
const END = "<!-- bank-stats:end -->";
const n = (x) => x.toLocaleString("en-GB");
const pct = (part, whole) => `${Math.round((100 * part) / whole)}%`;

const f = await bankFigures();
const [five, six] = f.lengths;
const row = (name, key, meaning) => `| ${name} | ${n(five[key])} | ${n(six[key])} | ${meaning} |`;
const block = `${START}
<!-- Generated by web/scripts/sync-readme.mjs. Run \`pnpm readme:sync\` after the bank changes. -->

**${n(f.answers)} answers** can be dealt as the puzzle: ${n(five.total)} five-letter and ${n(six.total)}
six-letter. Every one has a definition, a short note, two graded clues and a
difficulty. A further ${f.retired} are *retired* (never dealt, kept so earlier
solves still open to a full card). Players can guess from a much larger list of
**${n(f.dictionary)} words**, so a word does not have to be an answer to be accepted.

| Difficulty | 5-letter | 6-letter | Meaning |
| --- | ---: | ---: | --- |
${row("Familiar", "familiar", "nearly everyone knows it")}
${row("Stretch", "stretch", "many recognise it, few use it")}
${row("Challenging", "challenging", "most educated adults could not define it")}

${n(f.slang)} answers are slang, the rest standard. Pronunciation covers
${pct(f.coverage.pronunciation, f.answers)} of answers, part of speech ${pct(f.coverage.partOfSpeech, f.answers)}, origin
${pct(f.coverage.origin, f.answers)} and an example sentence ${pct(f.coverage.example, f.answers)} (${n(f.coverage.exampleFromTatoeba)} of them from Tatoeba).
${END}`;

const text = await readFile(README, "utf8");
const from = text.indexOf(START);
const to = text.indexOf(END);
if (from < 0 || to < 0) throw new Error("README.md is missing the bank-stats markers");
const next = text.slice(0, from) + block + text.slice(to + END.length);

if (process.argv.includes("--check")) {
  if (next !== text) {
    console.error("README.md figures are out of date with the word bank. Run: pnpm readme:sync");
    process.exit(1);
  }
  console.log("README figures match the word bank.");
} else {
  await writeFile(README, next);
  console.log(next === text ? "README already up to date." : "README figures updated.");
}
